package com.ianpedraza.masterrecylerview.utils

object RandomMessage {

    fun generate() = messages.random()

    private val messages = listOf(
        "A bird in the hand is worth two in the bush",
        "A bolt from the blue",
        "A bunch of fives",
        "A chain is only as strong as its weakest link",
        "A change is as good as a rest",
        "A country mile",
        "A countenance more in sorrow than in anger",
        "A Daniel come to judgement",
        "A diamond in the rough",
        "A diamond is forever",
        "A different kettle of fish",
        "Baby blues",
        "Baby boomer",
        "Baby father",
        "Back of beyond - The",
        "Back-seat driver",
        "Back the field",
        "Back to basics",
        "Back to square one",
        "Back to the drawing board",
        "Backroom boy",
        "Backward in coming forward",
        "Bacon",
        "Walk free",
        "Walk the walk",
        "Walk the plank",
        "Walkie-talkie",
        "Watching brief",
        "Wave a red rag to a bull",
        "Wax lyrical",
        "Wax poetic",
        "We are a grandmother",
        "We are not amused",
        "We few, we happy few, we band of brothers",
        "We have seen better days",
        "We know where you live",
        "San fairy Ann",
        "Sandwich short of a picnic",
        "Save face",
        "Save one's bacon",
        "Saved by the bell",
        "Savoir faire",
        "Say cheese",
        "Say goodnight Gracie",
        "Scapegoat",
        "Scarper",
        "Scot-free",
        "Mackerel sky",
        "Mad as a hatter",
        "Mad as a March hare",
        "Mad dogs and Englishmen go out in the midday sun",
        "Magical realism",
        "Main chance",
        "Make a bee-line for",
        "Make a clean breast of it",
        "Make a pig's ear of",
        "Make a rod for your own back",
        "Make a virtue of necessity",
        "Make haste",
        "Make hay while the sun shines",
        "Make him an offer he can't refuse",
        "Make my day",
        "Make no bones about",
        "Make your hair stand on end",
        "Mal de mer",
        "La-di-da",
        "Labour of love",
        "Lackadaisical",
        "Ladies' room",
        "La dolce vita",
        "Lager frenzy",
        "Laid out in lavender",
        "La-la land",
        "Lamb to the slaughter",
        "Lame duck",
        "Land-lubber",
        "Rabbit and pork",
        "Rack and ruin",
        "Rack your brains",
        "Rag-and-bone man",
        "Rag, tag and bobtail",
        "Raining cats and dogs",
        "Raining stair-rods",
        "Raise Cain",
        "Rank and file",
        "Raspberry tart",
        "Rat arsed",
        "Raze to the ground",
        "Razzle-dazzle",
        "Read between the lines",
        "Read the riot act",
        "Real McCoy",
        "Rearranging the deckchairs on the Titanic",
        "Red-handed (caught)",
        "Red-letter day",
        "Red herring",
        "Red in tooth and claw"
    ).shuffled()
}
